Change $WPAD_URLS to $PAC_URLS. Add support for DIRECT in $PAC_URLS. Add support for $HTTP_PROXIES. Change the default to not set -nv to wget. Only set -q on wget when getting PAC URL if -v or -d not set. Add error messages for when no proxy determined from $PAC_URLS and when URL is not successfully retrieved from somewhere. Fix setting of $RET to always be immediately after wget runs and not after the 'if' statement because that was always set to 0.

diff --git a/pacwget b/pacwget
--- a/pacwget
+++ b/pacwget
@@ -2,7 +2,7 @@
 # Wget wrapper to support Proxy Auto Config files, multiple proxies,
 #   and round-robin server names.
 # Requires wget, and pacparse command which is part of pacwget package
-# Written by Dave Dykstra, 21 March 2013
+# Written by Dave Dykstra, March 2013
 #
 # pacwget is free software; you can redistribute it and/or
 # modify it under the terms of the GNU Lesser General Public
@@ -24,13 +24,19 @@ ME=pacwget
 if [ $# = 0 ]; then
     echo "Usage: $ME [wget_options]" >&2
     echo >&2
-    echo '$WPAD_URLS is semicolon-separated list of URLs to read Web Proxy' >&2
-    echo '  Auto Discovery files from if $http_proxy is not set.' >&2
-    echo '  "auto" in the list is equivalent to http://wpad/wpad.dat' >&2
+    echo '$PAC_URLS is semicolon-separated list of URLs to read Proxy Auto Config' >&2
+    echo '  files from if $HTTP_PROXIES and $http_proxy are not set.' >&2
+    echo '  "auto" in the list is equivalent to http://wpad/wpad.dat and' >&2
+    echo '  "DIRECT" at the end indicates direct connection to server.' >&2
+    echo '  Default is "auto; DIRECT".' >&2
+    echo '$HTTP_PROXIES is a semicolon-separated list of http proxy URLs'. >&2
+    echo '  "DIRECT" at the end indicates direct connection to server.' >&2
+    echo '$http_proxy is single http proxy URL.' >&2
     echo 'For http:// URLs, tries all proxies and servers until one succeeds,' >&2
     echo '   including round-robin DNS names.' >&2
     echo 'By default adds these wget options:' >&2
-    echo '  --tries=1 --connect-timeout=5 --read-timeout=10 -nv' >&2
+    echo '  --tries=1 --connect-timeout=5 --read-timeout=10' >&2
+    echo 'Also adds wget -q when reading PAC URLs if -v or -d not given' >&2
     exit 1
 fi
 
@@ -40,7 +46,7 @@ PREV_ARG=""
 AHTTPURL=""
 IPVERSION=""
 PACPARSEDEBUG=""
-WGETVERBOSE=""
+PACWGETQUIET="-q"
 for ARG; do
     case "$PREVARG" in
 	-*T*)
@@ -64,9 +70,10 @@ for ARG; do
 	    ;;
 	--debug|-d)
 	    PACPARSEDEBUG="-d"
+	    PACWGETQUIET=""
 	    ;;
 	--verbose|-v)
-	    WGETVERBOSE="-v"
+	    PACWGETQUIET=""
 	    ;;
 	http://*)
 	    if [ -z "$AHTTPURL" ]; then
@@ -76,7 +83,7 @@ for ARG; do
     esac
 done
 
-PACWGETARGS="--tries=1 -q"
+PACWGETARGS="--tries=1 $PACWGETQUIET"
 WGETARGS="--tries=1"
 if [ -n "$CONNECTTIMEOUT" ]; then
     PACWGETARGS="$PACWGETARGS --connect-timeout=$CONNECTTIMEOUT"
@@ -93,31 +100,33 @@ fi
 if [ -n "$PACPARSEDEBUG" ]; then
     PACWGETARGS="$PACWGETARGS -d"
 fi
-if [ -z "$WGETVERBOSE" ]; then
-    WGETARGS="$WGETARGS -nv"
-fi
 
 if [ -z "$AHTTPURL" ]; then
     exec wget $WGETARGS "$@"
 fi
 
-if [ -n "$http_proxy" ]; then
+if [ -n "$HTTP_PROXIES" ]; then
+    PROXIES="${HTTP_PROXIES//;/ }"
+elif [ -n "$http_proxy" ]; then
     PROXIES="$http_proxy"
 else
-    if [ -z "$WPAD_URLS" ]; then
-	WPAD_URLS="auto"
+    if [ -z "$PAC_URLS" ]; then
+	PAC_URLS="auto; DIRECT"
     fi
     PACTMPFILE=`mktemp /tmp/pacwgetXXXXXXXXXX`
     trap "rm -f $PACTMPFILE" 0
-    for WPADURL in ${WPAD_URLS//;/ }; do
-	if [ "$WPADURL" = "auto" ]; then
-	    WPADURL="http://wpad/wpad.dat"
+    for PACURL in ${PAC_URLS//;/ }; do
+	if [ "$PACURL" = "auto" ]; then
+	    PACURL="http://wpad/wpad.dat"
+	elif [ "$PACURL" = "DIRECT" ]; then
+	    PROXIES="DIRECT"
+	    break
 	fi
 	if [ -n "$PACPARSER_DEBUG" ]; then
-	    echo "DEBUG: wgetting $WPADURL"
+	    echo "DEBUG: wgetting $PACURL"
 	fi
-	if wget $PACWGETARGS -O$PACTMPFILE $WPADURL; then
-	    if PROXYLIST="`pacparse $IPVERSION $PACPARSEDEBUG -p $PACTMPFILE -u "$AHTTPURL" -U "$WPADURL"`"; then
+	if wget $PACWGETARGS -O$PACTMPFILE $PACURL; then
+	    if PROXYLIST="`pacparse $IPVERSION $PACPARSEDEBUG -p $PACTMPFILE -u "$AHTTPURL" -U "$PACURL"`"; then
 		case "$PROXYLIST" in
 		    "PROXY "*|"DIRECT")
 			PROXIES="${PROXYLIST//PROXY /}"
@@ -125,7 +134,7 @@ else
 			break
 			;;
 		esac
-		echo "$ME: proxy auto config parse of $WPADURL" >&2
+		echo "$ME: proxy auto config parse of $PACURL" >&2
 		echo "  with URL $AHTTPURL" >&2
 		echo "  did not return list starting with PROXY or DIRECT" >&2
 		echo "  Instead it returned: $PROXYLIST" >&2
@@ -133,6 +142,10 @@ else
 	    fi
 	fi
     done
+    if [ -z "$PROXIES" ]; then
+	echo "$ME: no proxy found from PAC_URLS=\"$PAC_URLS\"" >&2
+	exit 2
+    fi
     rm -f $PACTMPFILE
     trap 0
 fi
@@ -141,16 +154,17 @@ fi
 # It would nice to be able to execute wget once for all URLs, but it sometimes
 #  returns success even if one of the URLs fails.  Also, it never reuses a
 #  connection to a proxy anyway so it doesn't make a huge difference.  At
-#  least the list of proxies determined from the WPAD above can be reused
+#  least the list of proxies determined above can be reused
 RET=0
 for ARG; do
     case "$ARG" in
 	http://*);;
 	*://*)
-	    if wget $WGETARGS "$ARG"; then
+	    wget $WGETARGS "$ARG"
+	    RET=$?
+	    if [ $RET = 0 ]; then
 		continue
 	    fi
-	    RET=$?
 	    break
 	    ;;
 	*)
@@ -166,10 +180,11 @@ for ARG; do
 	else
 	    export http_proxy="$PROXY"
 	fi
-	if wget $WGETARGS "$ARG"; then
+	wget $WGETARGS "$ARG"
+	RET=$?
+	if [ $RET = 0 ]; then
 	    break
 	fi
-	RET=$?
 	if [ "$PROXY" != DIRECT ]; then
 	    # if using a proxy, and server has more than one address,
 	    #  try individual addresses too if can find them, to make
@@ -183,19 +198,25 @@ for ARG; do
 	    fi
 	    for IP in $IPS; do
 		RET=0
-		if wget $WGETARGS "${ARG/$AHOST/$IP}"; then
+		wget $WGETARGS "${ARG/$AHOST/$IP}"
+		RET=$?
+		if [ $RET = 0 ]; then
 		    break
 		fi
-		RET=$?
 	    done
-	    if [ $RET -eq 0 ]; then
+	    if [ $RET = 0 ]; then
 		break
 	    fi
 	fi
-	if [ $RET -eq 0 ]; then
+	if [ $RET = 0 ]; then
 	    break
 	fi
     done
+    if [ $RET != 0 ]; then
+	echo "$ME: error getting $ARG" >&2
+	echo "  with HTTP_PROXIES=${PROXIES// /; }" >&2
+	break
+    fi
 done
 
 exit $RET
